<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search Amazon_nav-search-submit-button</name>
   <tag></tag>
   <elementGuidId>6068fd76-a38e-4440-b014-5daa86f11459</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-search-submit-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nav-search-submit-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5fb031d-f35a-4272-9790-f771ae278ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-search-submit-button</value>
      <webElementGuid>3431947e-ddf9-4543-8d8d-ce4c7e9243c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>748adc6b-1987-4b61-a336-24fecc254925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-input nav-progressive-attribute</value>
      <webElementGuid>b3593ca7-2368-421d-9edb-2bb4dcd0f4e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Go</value>
      <webElementGuid>1f4b0e77-11e4-4ba6-a023-12c058dffc92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6b993436-9d64-4efc-b8c1-2522acd6704c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-search-submit-button&quot;)</value>
      <webElementGuid>5fedb1ee-479e-42cb-a61e-63f047aca14d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nav-search-submit-button']</value>
      <webElementGuid>2e6d0fb9-653c-4a74-8a69-d9e96eed737b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='nav-search-submit-text']/input</value>
      <webElementGuid>8445e6ad-5496-4c70-8f0d-28b572cf22e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>2400b977-767c-44b7-b022-190bfbb73031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nav-search-submit-button' and @type = 'submit']</value>
      <webElementGuid>979ff567-a3e5-4d06-89b5-ee501504635f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
