<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_valentines day gifts for her</name>
   <tag></tag>
   <elementGuidId>f8830b9b-b23d-406c-a47e-1ba71d3b0bfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.s-heavy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-flyout-searchAjax']/div[2]/div/div/div/div/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>079c864b-d6cb-4e2c-a187-d5bc47392fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s-heavy</value>
      <webElementGuid>51b923c1-2642-43ad-b793-a0d4a09c7004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>valentines day gifts for her</value>
      <webElementGuid>85b13b21-ebfb-46bb-af0e-acfcaae6ecba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-flyout-searchAjax&quot;)/div[@class=&quot;autocomplete-results-container&quot;]/div[@class=&quot;two-pane-results-container&quot;]/div[@class=&quot;left-pane-results-container&quot;]/div[1]/div[@class=&quot;s-suggestion-trending-container&quot;]/div[@class=&quot;s-suggestion-trending s-suggestion-ellipsis-direction&quot;]/span[@class=&quot;s-heavy&quot;]</value>
      <webElementGuid>7e4b4053-655b-4eb0-92ca-e6f34e525724</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-flyout-searchAjax']/div[2]/div/div/div/div/div[2]/span</value>
      <webElementGuid>17e5ffb3-6b4c-42a9-8a9f-3d0877326af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/span</value>
      <webElementGuid>6ce1c178-1882-4a9c-a686-8c9982a78898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'valentines day gifts for her' or . = 'valentines day gifts for her')]</value>
      <webElementGuid>15b274cf-b313-4e1e-ad51-63ba0d0132e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
