<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_5,687 ratings</name>
   <tag></tag>
   <elementGuidId>1e3cfb8a-76e5-4f5f-a01c-93a66bf5075b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#acrCustomerReviewText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='acrCustomerReviewText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>09859bb6-166d-4bfe-bd7c-40f887886d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acrCustomerReviewText</value>
      <webElementGuid>ce1b9bc7-5910-49c6-adb3-cb11aee9b2bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-size-base</value>
      <webElementGuid>d9d4c2b2-2876-4fec-87fa-c16d1c90e578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5,687 ratings</value>
      <webElementGuid>6a262fbe-5ab0-4037-a5c7-58bb6b9f8b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;averageCustomerReviews_feature_div&quot;)/div[@id=&quot;averageCustomerReviews&quot;]/span[@class=&quot;a-declarative&quot;]/a[@id=&quot;acrCustomerReviewLink&quot;]/span[@id=&quot;acrCustomerReviewText&quot;]</value>
      <webElementGuid>648b3778-5a25-42ed-8a7d-bce891b408fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='acrCustomerReviewText']</value>
      <webElementGuid>c1e89cc6-0ba3-4c6d-8555-ca580b0871e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='acrCustomerReviewLink']/span</value>
      <webElementGuid>448618b0-e6b3-450c-8008-52f0be238095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/a/span</value>
      <webElementGuid>20088c06-a9a9-4931-ac4f-1ef51a25ce9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'acrCustomerReviewText' and (text() = '5,687 ratings' or . = '5,687 ratings')]</value>
      <webElementGuid>40639d1f-9879-46d0-8ef7-1922478ce306</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
